/*
ATTENTION NE PAS TOUCHER A CES LIGNES
*/

BEGIN   
EXECUTE IMMEDIATE 'DROP TABLE JOUER';
EXCEPTION  
 WHEN OTHERS THEN      
	IF SQLCODE != -942 THEN         
	RAISE;      
	END IF;
END;
/


BEGIN   
EXECUTE IMMEDIATE 'DROP TABLE FILM';
EXCEPTION  
 WHEN OTHERS THEN      
	IF SQLCODE != -942 THEN         
	RAISE;      
	END IF;
END;
/

BEGIN   
EXECUTE IMMEDIATE 'DROP TABLE ACTEUR';
EXCEPTION  
 WHEN OTHERS THEN      
	IF SQLCODE != -942 THEN         
	RAISE;      
	END IF;
END;
/

BEGIN   
EXECUTE IMMEDIATE 'DROP TABLE REALISATEUR';
EXCEPTION  
 WHEN OTHERS THEN      
	IF SQLCODE != -942 THEN         
	RAISE;      
	END IF;
END;
/

BEGIN   
EXECUTE IMMEDIATE 'DROP TABLE GENRE';
EXCEPTION  
 WHEN OTHERS THEN      
	IF SQLCODE != -942 THEN         
	RAISE;      
	END IF;
END;
/

/*
FIN DE ATTENTION NE PAS TOUCHER A CES LIGNES
*/

/* 
CREATION EN PREMIER DES RELATIONS STATIQUES 
*/
prompt ---------------------------------;
prompt -- CREATION DE LA TABLE ACTEUR --;
prompt ---------------------------------;
CREATE TABLE ACTEUR (
	IDA NUMERIC(2,0), 
	NOM VARCHAR(50) NOT NULL, 
	PRENOM VARCHAR(50) NOT NULL,
	NATIONALITE VARCHAR(10),
    CONSTRAINT PK_AUTEUR PRIMARY KEY(IDA)
);

prompt --------------------------------------;
prompt -- CREATION DE LA TABLE REALISATEUR --;
prompt --------------------------------------;
CREATE TABLE REALISATEUR (
	IDR NUMERIC(2,0), 
	NOM VARCHAR(50) NOT NULL, 
	PRENOM VARCHAR(50) NOT NULL,
	NATIONALITE VARCHAR(10),
    CONSTRAINT PK_REALISATEUR PRIMARY KEY(IDR)
);


prompt --------------------------------;
prompt -- CREATION DE LA TABLE GENRE --;
prompt --------------------------------;
CREATE TABLE GENRE (
	IDG NUMERIC(2,0), 
	DESCRIPTION VARCHAR(50) NOT NULL,
    CONSTRAINT PK_GENRE PRIMARY KEY(IDG)
);


/* 
CREATION EN SECOND DES RELATIONS DYNAMIQUES 
*/

prompt -------------------------------;
prompt -- CREATION DE LA TABLE FILM --;
prompt -------------------------------;

CREATE TABLE FILM (
	IDF NUMERIC(2,0), 
	TITRE VARCHAR(50) NOT NULL, 
	ANNEE NUMERIC(20,0),
	PAYS VARCHAR(10),
    NBSPECTATEURS NUMERIC(30,0),
    IDREALISATEUR NUMERIC(2,0), 
    IDGENRE NUMERIC(2,0), 
    CONSTRAINT PK_FILM PRIMARY KEY(IDF),
    CONSTRAINT FK_FILM_REALISATEUR FOREIGN KEY (IDREALISATEUR) REFERENCES REALISATEUR (IDR),
    CONSTRAINT FK_FILM_GENRE FOREIGN KEY (IDGENRE) REFERENCES GENRE (IDG)
);

prompt --------------------------------;
prompt -- CREATION DE LA TABLE JOUER --;
prompt --------------------------------;


CREATE TABLE JOUER (
	IDACTEUR NUMERIC(2,0), 
	IDFILM NUMERIC(2,0),
    CONSTRAINT PK_JOUER PRIMARY KEY(IDACTEUR,IDFILM),
    CONSTRAINT FK_JOUER_ACTEUR FOREIGN KEY (IDACTEUR) REFERENCES ACTEUR (IDA),
    CONSTRAINT FK_JOUER_FILM FOREIGN KEY (IDFILM) REFERENCES FILM (IDF),
	SALAIRE NUMERIC(5)
);

SET LINESIZE 500;

INSERT INTO ACTEUR VALUES (1, 'Bob', 'Omb', 'Français');
INSERT INTO ACTEUR VALUES (2, 'Jean', 'Michou', 'Français');
INSERT INTO ACTEUR VALUES (3, 'Jack', 'L''Eventreur', 'Anglais');
INSERT INTO ACTEUR VALUES (4, 'Juan', 'DeLaVega', 'Espagnole');
INSERT INTO ACTEUR VALUES (5, 'Adele', 'Frigide', 'Français');
INSERT INTO ACTEUR VALUES (6, 'Jacky', 'San', 'Japonais');

INSERT INTO REALISATEUR VALUES (1, 'Hamiral', 'Hamster', 'HamsterLand');
INSERT INTO REALISATEUR VALUES (2, 'Jean', 'Serieux', 'Français');
INSERT INTO REALISATEUR VALUES (3, 'Minou', 'Miaou', 'KittyLand');
INSERT INTO REALISATEUR VALUES (4, 'Antoine', 'Gouyon', 'Mordor');
INSERT INTO REALISATEUR VALUES (5, 'Pikachu', 'Sama', 'Johto');
INSERT INTO REALISATEUR VALUES (6, 'Chin', 'Chan', 'Chinois');

INSERT INTO GENRE VALUES (1, 'Policier');
INSERT INTO GENRE VALUES (2, 'Horreur');
INSERT INTO GENRE VALUES (3, 'Fantasy');
INSERT INTO GENRE VALUES (4, 'Thriller');
INSERT INTO GENRE VALUES (5, 'Romance');
INSERT INTO GENRE VALUES (6, 'NamNamNam');

INSERT INTO FILM VALUES (1, 'La Maman en Short', 1992, 10000, 1, 1);
INSERT INTO FILM VALUES (2, 'Fast And Fouras 42', 1992, 9000, 1, 1);
INSERT INTO FILM VALUES (3, 'Fantasy Final™', 1992, 2, 1, 1);
INSERT INTO FILM VALUES (4, 'Le trou', 1992, 2, 1, 1);
INSERT INTO FILM VALUES (5, 'NamLand', 1992, 2, 1, 1);
INSERT INTO FILM VALUES (6, 'Adriaaaaaaane', 1992, 2, 1, 1);
