default:
	make -f make_1
	make -f make_2
	make -f make_3

clean:
	make -f make_1 clean
	make -f make_2 clean
	make -f make_3 clean

mrproper:
	make -f make_1 mrproper
	make -f make_2 mrproper
	make -f make_3 mrproper